### ISSUE TITLE
kubectl apply -f dify-deployment.yaml failed error

### ISSUE THREAD

**Issue by stever100** [Winson-030/dify-kubernetes#1]
it seems error in kubectl apply
The request is invalid: patch: Invalid value: "map[spec:map[template:map[spec:map[]] volumes:[map[hostPath:map[path:/root/dify/app/api/storage type:DirectoryOrCreate] name:dify-api-storage]]]]": strict decoding error: unknown field "spec.volumes"

**Comment by Winson-030** [comment]
> it seems error in kubectl apply The request is invalid: patch: Invalid value: "map[spec:map[template:map[spec:map[]] volumes:[map[hostPath:map[path:/root/dify/app/api/storage type:DirectoryOrCreate] name:dify-api-storage]]]]": strict decoding error: unknown field "spec.volumes"
Hi, fixed in this commit. 
[https://github.com/Winson-030/dify-kubernetes/commit/4940141967078757371cb6a8fb1747fdbc99b49b](https://github.com/Winson-030/dify-kubernetes/commit/4940141967078757371cb6a8fb1747fdbc99b49b)

**Comment by stever100** [comment]
thanks. yes, working now, no more error in applying
