### ISSUE TITLE
pull image error

### ISSUE THREAD

**Issue by dataknocker** [Winson-030/dify-kubernetes#10]
docker pull docker.kubesre.xyz/postgres:15-alpine
Error response from daemon: denied

**Comment by Winson-030** [comment]
Can you verify whether the mirror domain kubesre.xyz accessible?
Maybe I should change another mirror if inaccessible.

**Comment by dataknocker** [comment]
注意： dockerhub仓库的别名：docker.kubesre.xyz被墙，更换成：dhub.kubesre.xyz

**Comment by Winson-030** [comment]
Great! I'll update it.

**Comment by Winson-030** [comment]
updated mirror in commit , close issue.
