### ISSUE TITLE
Unable to connect to the dify-web as its starting in Node IP

### ISSUE THREAD

**Issue by abhishek-ch** [Winson-030/dify-kubernetes#13]
I am struggling to port-forward on the web or ingress.
Further investigation showed me that the web app is not actually starting on 0.0.0.0 but the node ip

```
11:34:06 1|dify-web  |   ▲ Next.js 14.2.4
11:34:06 1|dify-web  |   - Local:        http://dify-web-sdsds-92cmx:3000
11:34:06 1|dify-web  |   - Network:      http://SOMEIP:3000
```

How can I avoid it? Any suggestion?

**Comment by Winson-030** [comment]
@abhishek-ch this is because you there is pod ip or container service name in the log. Just port forward the dify web deployment service or create a node port service for the dify web deployment. Feel free to comment if you need more help. 😉

**Comment by abhishek-ch** [comment]
Well since I am very confused why even nodeport service not working, I simply create a deployment with dify-web and tried everything but not sure why can I connect to the web


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-web
  labels:
    app: abc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-web
  template:
    metadata:
      labels:
        app: abc-web
    spec:
      containers:
      - name: abc-web
        image: langgenius/dify-web:0.9.1
        ports:
        - containerPort: 3000
        env:
        - name: CONSOLE_API_URL
          value: "http://dify-api-service:5001"
        - name: APP_API_URL
          value: "http://dify-api-service:5001"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: TEXT_GENERATION_TIMEOUT_MS
          value: "60000"
---
apiVersion: v1
kind: Service
metadata:
  name: abc-web-service
spec:
  selector:
    app: abc-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: abc-web-nodeport
  labels:
    app: abc-web
spec:
  type: NodePort
  selector:
    app: abc-web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
```

any suggestion, why port frwd is not working

my logs
```
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
2024-10-08T13:31:44: PM2 log: Launching in no daemon mode
2024-10-08T13:31:44: PM2 log: [PM2][WARN] Applications dify-web not running, starting...
2024-10-08T13:31:44: PM2 log: App [dify-web:0] starting in -cluster mode-
2024-10-08T13:31:44: PM2 log: App [dify-web:0] online
2024-10-08T13:31:44: PM2 log: App [dify-web:1] starting in -cluster mode-
2024-10-08T13:31:44: PM2 log: App [dify-web:1] online
2024-10-08T13:31:44: PM2 log: [PM2] App [dify-web] launched (2 instances)
2024-10-08T13:31:44: PM2 log: ┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ dify-web    │ default     │ 0.9.1   │ cluster │ 18       │ 0s     │ 0    │ online    │ 0%       │ 52.1mb   │ root     │ disabled │
│ 1  │ dify-web    │ default     │ 0.9.1   │ cluster │ 25       │ 0s     │ 0    │ online    │ 0%       │ 49.8mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
2024-10-08T13:31:44: PM2 log: [--no-daemon] Continue to stream logs
2024-10-08T13:31:44: PM2 log: [--no-daemon] Exit on target PM2 exit pid=7
13:31:45 0|dify-web  |   ▲ Next.js 14.2.4
13:31:45 0|dify-web  |   - Local:        http://abc-web-85dcd597c6-nhqw9:3000
13:31:45 0|dify-web  |   - Network:      http://<IP>:3000
13:31:45 0|dify-web  |  ✓ Starting...
13:31:45 1|dify-web  |   ▲ Next.js 14.2.4
13:31:45 1|dify-web  |   - Local:        http://abc-web-85dcd597c6-nhqw9:3000
13:31:45 1|dify-web  |   - Network:      http://<IP>:3000
13:31:45 1|dify-web  |  ✓ Starting...
13:31:45 0|dify-web  |  ✓ Ready in 189ms
13:31:45 1|dify-web  |  ✓ Ready in 159m
```

**Comment by Winson-030** [comment]
> Well since I am very confused why even nodeport service not working, I simply create a deployment with dify-web and tried everything but not sure why can I connect to the web
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: abc-web
>   labels:
>     app: abc-web
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: abc-web
>   template:
>     metadata:
>       labels:
>         app: abc-web
>     spec:
>       containers:
>       - name: abc-web
>         image: langgenius/dify-web:0.9.1
>         ports:
>         - containerPort: 3000
>         env:
>         - name: CONSOLE_API_URL
>           value: "http://dify-api-service:5001"
>         - name: APP_API_URL
>           value: "http://dify-api-service:5001"
>         - name: NEXT_TELEMETRY_DISABLED
>           value: "1"
>         - name: TEXT_GENERATION_TIMEOUT_MS
>           value: "60000"
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: abc-web-service
> spec:
>   selector:
>     app: abc-web
>   ports:
>     - protocol: TCP
>       port: 80
>       targetPort: 3000
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: abc-web-nodeport
>   labels:
>     app: abc-web
> spec:
>   type: NodePort
>   selector:
>     app: abc-web
>   ports:
>     - port: 3000
>       targetPort: 3000
>       nodePort: 30000
> ```
> 
> any suggestion, why port frwd is not working
> 
> my logs
> 
> ```
> pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
> 2024-10-08T13:31:44: PM2 log: Launching in no daemon mode
> 2024-10-08T13:31:44: PM2 log: [PM2][WARN] Applications dify-web not running, starting...
> 2024-10-08T13:31:44: PM2 log: App [dify-web:0] starting in -cluster mode-
> 2024-10-08T13:31:44: PM2 log: App [dify-web:0] online
> 2024-10-08T13:31:44: PM2 log: App [dify-web:1] starting in -cluster mode-
> 2024-10-08T13:31:44: PM2 log: App [dify-web:1] online
> 2024-10-08T13:31:44: PM2 log: [PM2] App [dify-web] launched (2 instances)
> 2024-10-08T13:31:44: PM2 log: ┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
> │ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
> ├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
> │ 0  │ dify-web    │ default     │ 0.9.1   │ cluster │ 18       │ 0s     │ 0    │ online    │ 0%       │ 52.1mb   │ root     │ disabled │
> │ 1  │ dify-web    │ default     │ 0.9.1   │ cluster │ 25       │ 0s     │ 0    │ online    │ 0%       │ 49.8mb   │ root     │ disabled │
> └────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
> 2024-10-08T13:31:44: PM2 log: [--no-daemon] Continue to stream logs
> 2024-10-08T13:31:44: PM2 log: [--no-daemon] Exit on target PM2 exit pid=7
> 13:31:45 0|dify-web  |   ▲ Next.js 14.2.4
> 13:31:45 0|dify-web  |   - Local:        http://abc-web-85dcd597c6-nhqw9:3000
> 13:31:45 0|dify-web  |   - Network:      http://<IP>:3000
> 13:31:45 0|dify-web  |  ✓ Starting...
> 13:31:45 1|dify-web  |   ▲ Next.js 14.2.4
> 13:31:45 1|dify-web  |   - Local:        http://abc-web-85dcd597c6-nhqw9:3000
> 13:31:45 1|dify-web  |   - Network:      http://<IP>:3000
> 13:31:45 1|dify-web  |  ✓ Starting...
> 13:31:45 0|dify-web  |  ✓ Ready in 189ms
> 13:31:45 1|dify-web  |  ✓ Ready in 159m
> ```
> 
> Error on Port fwd
> 
> ```
> Forwarding from 127.0.0.1:3000 -> 3000
> Forwarding from [::1]:3000 -> 3000
> Handling connection for 3000
> E1009 12:24:36.171125   81441 portforward.go:413] "Unhandled Error" err="an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod 737a83c7b741a63a0abc12133c78ea88930a25b429382f6296eb8fab0c13ffa0, uid : failed to execute portforward in network namespace \"/var/run/netns/cni-8446eb2c-1231-5de1-360b-cff5646619fb\": failed to connect to localhost:3000 inside namespace \"737a83c7b741a63a0abc12133c78ea88930a25b429382f6296eb8fab0c13ffa0\", IPv4: dial tcp4 127.0.0.1:3000: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found "
> error: lost connection to pod
> ```
> 
> _BDW, I managed to hack it by instructing the IP tables to reroute IP to 0.0.0.0:3000, not sure its a good hack or not but I gotta make it work_

Alright, seems your cluster dns did not assign ip to the pod. if you apply my prepared command this would not happend, I have create a nodeport service and you can access dify with `node_ip:3000`. BTW, you did a good job! I will close this issue with fixed.
