### ISSUE TITLE
删除应用的时候报错Port could not be cast to integer value as '$(REDIS_PORT)'，刷新下应用确实呗删除了

### ISSUE THREAD

**Issue by qiyigang** [Winson-030/dify-kubernetes#15]
检查了dify-api的yaml 和日志 
日志里只有2024-10-28 02:04:57,220.220 INFO [Thread-32 (process_request_thread)] [_internal.py:97] - 10.42.22.106 - - [28/Oct/2024 02:04:57] "DELETE /console/api/apps/62308388-1b29-4eb8-8e75-b9033705d4a2 HTTP/1.1" 400 -
![image](https://github.com/user-attachments/assets/d7156a2f-e189-4e28-9831-eec3a3ee3bdb)

**Comment by Winson-030** [comment]
Please share more detailed logs here.
