### ISSUE TITLE
请教一下，我想把节点变成无状态节点，需要调整哪些功能

### ISSUE THREAD

**Issue by froest2012** [Winson-030/dify-kubernetes#3]

**Comment by Winson-030** [comment]
将statefulset 改成 deployment 即可，其他不变。
一般建议数据库之类的服务用statefulset，确保数据的安全

**Comment by qiyigang** [comment]
我用K8S部署 吧所有hostpath挂载全部换成storageclass 其他没变   启动以后访问/install  跳转到
![image](https://github.com/user-attachments/assets/1ebf3b8d-83de-4877-91ca-765564a516f3)
 输入密码返回401 也没看到api有什么报错日志 
![image](https://github.com/user-attachments/assets/a5281850-0cd0-4bec-8eae-214f3055c597)

**Comment by Winson-030** [comment]
默认是password，你看看有没有改

**Comment by qiyigang** [comment]
谢谢 这个是什么配置里面控制的 没看到啊， docker-compose起的时候没这个东西

**Comment by Winson-030** [comment]
> 谢谢 这个是什么配置里面控制的 没看到啊， docker-compose起的时候没这个东西
> 
> 
> 
> 

环境变量配的，可以自定义的。我配的默认是password
