### ISSUE TITLE
关于知识库上传文件失败的原因

### ISSUE THREAD

**Issue by Zgy6954** [Winson-030/dify-kubernetes#5]
在dify-deployment.yaml中，dify-worker和dify-api两个应用的hostPath如果设置为/root/dify/app/api/storage，在知识库中上传文件会提示失败，需要将hostPath目录改成和mountPath一致，/root/dify/app/api/storage 改成 /app/api/storage 即可解决问题。
可参考：https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/environments#wen-jian-cun-chu-pei-zhi

**Comment by Winson-030** [comment]
谢谢建议，似乎这是权限问题。我在开发的时候集群节点的用户默认是root，所以配置文件上写了root用户的路径。修改路径即可解决问题。

**Translation**

Thank you for the suggestion, it seems this is a permissions issue. The default user for the cluster node is root in my dev cluster, so the yaml file specifies the path under the root directory. Change the host path cloud fix this issue.
