### ISSUE TITLE
is mutiple postregsql and redis pods supported?

### ISSUE THREAD

**Issue by TheZhuangPark** [Winson-030/dify-kubernetes#6]
with mutiple postregsql and redis pods, which can enhance the stability of Dify

**Comment by Winson-030** [comment]
Currently not. This is a very good idea to setup HA components, I will consider this in the future. Now You can deploy HA db by yourself and deploy other components separately. Deployment yaml files are in folder 'dify/'. 
Very welcome to raise PR, big thanks! ❤️

**Comment by Winson-030** [comment]
Kubeblock maybe a good choice

**Comment by TheZhuangPark** [comment]
> Currently not. This is an very good idea to setup HA components, I will consider this in the future. Now You can deploy HA db by yourself and deploy other components separately. Deployment yaml files are in folder 'dify/'. Very welcome to raise PR, big thanks! ❤️

**Comment by TheZhuangPark** [comment]
i am currently working on it, cause most people deploy dify on k8s normall will need mutiple instances of components.
i hope to commit some yaml file, mostly focus on expansion of postregsql and redis(HA DB),i currently working on my 10+ ubuntu  mechines. 
1 use Patroni as control layer of multiple postregsql. 
2 native clustering feature as redis cluster
how is that?

**Comment by Winson-030** [comment]
Sure! Welcome raise PRs! Please add files under folder dify/ first. I think it is good to have a new deployment yaml file for HA setup. I will work with you on this case.
