### ISSUE TITLE
dify-weaviate CrashLoopBackOff 

### ISSUE THREAD

**Issue by gptbert** [Winson-030/dify-kubernetes#9]
dify-weaviate CrashLoopBackOff when kubectl apply -f https://cdn.jsdelivr.net/gh/Winson-030/dify-kubernetes@main/dify-mirror-deployment.yaml

NAME                            READY   STATUS             RESTARTS        AGE
dify-api-0                      1/1     Running            0               19m
dify-nginx-64c7c7d7d5-qkwl4     1/1     Running            0               19m
dify-pg-0                       1/1     Running            0               19m
dify-redis-0                    1/1     Running            0               19m
dify-sandbox-7686cc64f8-jnk2j   1/1     Running            0               19m
dify-ssrf-689964c788-pfx9w      1/1     Running            0               19m
dify-weaviate-0                 0/1     CrashLoopBackOff   8 (3m18s ago)   19m
dify-web-796cdd6c9-68mxq        1/1     Running            0               19m
dify-worker-0                   1/1     Running            0               19m

kubectl logs -p dify-weaviate-0 -n dify

{"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-08-22T03:42:06Z"}
{"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-08-22T03:42:06Z"}
{"action":"memberlist_init","bind_port":7946,"error":"Failed to get final advertise address: No private IP address found, and explicit IP not provided","hostname":"","level":"error","msg":"memberlist not created","time":"2024-08-22T03:42:06Z"}
{"action":"startup","error":"create member list: Failed to get final advertise address: No private IP address found, and explicit IP not provided","level":"error","msg":"could not init cluster state","time":"2024-08-22T03:42:06Z"}

**Comment by Winson-030** [comment]
{"action":"startup","error":"create member list: Failed to get final advertise address: No private IP address found, and explicit IP not provided","level":"error","msg":"could not init cluster state","time":"2024-08-22T03:42:06Z"}


This is the root cause of the issue, no private ip assigned.
